services:
  backend:
    build: rust
    container_name: backend-rust
    restart: always
    networks:
      - backend-network

  nginx:
    build: nginx
    container_name: backend-nginx
    restart: always
    environment:
      - HOST=api.felysneko.com
    ports:
      - 443:443
      - 80:80
    networks:
      - backend-network

networks:
  backend-network:
    name: backend-network
