services:
  axum:
    build: axum
    container_name: backend-axum
    restart: always
    networks:
      - backend-network

  fast:
    build: fast
    container_name: backend-fast
    restart: always
    networks:
      - backend-network

  nginx:
    build: nginx
    container_name: backend-nginx
    restart: always
    environment:
      - HOST=api.felysneko.com
    ports:
      - 443:443
      - 80:80
    networks:
      - backend-network

networks:
  backend-network:
    name: backend-network
