version: "3.7"

services:
  backend:
    build: frontend
    container_name: frontend-server
    restart: always
    networks:
      - frontend-network

  nginx:
    build: nginx
    container_name: frontend-nginx
    restart: always
    environment:
      - HOST=felysneko.com www.felysneko.com
    ports:
      - 443:443
      - 80:80
    networks:
      - frontend-network

networks:
  frontend-network:
    name: frontend-network
